spring:
  application:
    name: oauth2-sso-client-member-produce
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_oauth?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://glj:glj@127.0.0.1:2100/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#swagger
swagger2:
  enable: true