server:
  port: 8084
spring:
  application:
    name: api-gateway

#Zuul
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    member:
      path: /member/**
      serviceId: oauth2-sso-client-member
      sensitiveHeaders:
  
##eureka
eureka:
  client:
    service-url:
      defaultZone: http://glj:glj@127.0.0.1:2100/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}