spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_oauth?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    password: test
    username: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080