spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_oauth?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    password: test
    username: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  application:
    name: authentication-center
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://glj:glj@127.0.0.1:2100/eureka/