server:
  port: 8082
#  servlet:
#    context-path: /memberSystem
security:
  oauth2:
    client:
      client-id: UserManagement
      client-secret: user123
      access-token-uri: http://172.23.23.14:8080/oauth/token
      user-authorization-uri: http://172.23.23.14:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://172.23.23.14:8080/oauth/token_key
spring:
  application:
    name: oauth2-sso-client-member
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security_oauth?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #模板引擎配置
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
    request-context-attribute: rc
    charset: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://glj:glj@127.0.0.1:2100/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
