server:
  port: 8083
  servlet:
    context-path: /orderSystem
security:
  oauth2:
    client:
      client-id: OrderManagement
      client-secret: order123
      access-token-uri: http://127.0.0.1:8080/oauth/token
      user-authorization-uri: http://127.0.0.1:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8080/oauth/token_key